### ISSUE TITLE
Geometric Shapes in Raymarch

### ISSUE THREAD

**Issue by jjxtra** [sebh/TileableVolumeNoise#1]
I've been comparing the shape noise from this library versus other libraries. The shape noise generated from this code generates stars, squares and other hard edges and shapes in the clouds. Other noise generated from other code base does not seem to have this severe of an issue. The erosion noise does not seem to have this problem. Any ideas?

**Comment by sebh** [comment]
Hi,
No idea and hard to tell without seeing it. I have never seen such pattern myself (does not mean there is no problem though).
I see this closed so I guess the issue was coming from something else and you figured it out?

**Comment by jjxtra** [comment]
Are the textures meant to be seamless?

I mostly fixed it, but I still see some hard edges and shapes, but that may be more my shader at this point. Is the packed shape (perlin/worley .r channel and worley gba channel) tga meant to only have values from 200-255? It seems very bright. Just wanted to make sure that is expected. Here is an example of some of the hard edges I am seeing (unlit clouds):

![image](https://user-images.githubusercontent.com/1271832/47091809-d586de80-d1e2-11e8-9251-72854fa60d9c.png)

**Comment by sebh** [comment]
In the noiseErosion texture, I have values that are {90, 89, 234} for instance so no it is varying.

For noiseShapePacked, yes it is a bit bright and this comes from the way we generate the noise with octave: allways additive with: value = worleyFBM0*0.625 + worleyFBM1*0.25 + worleyFBM2*0.125.
It is correct though. But you can change it if you want, there are no rule when generating noise. Or you can also remap the value from min/max to 0/1. I could add that option maybe?

In you image: all I am seeing is linear interpolation of texture being more visible probably due to some remapping/thesholding you are doing I guess.
You do loas this images in 3Dtexture right? because using them in 2d would show seams in between each slice (due to the way it is flattened).

**Comment by jjxtra** [comment]
It is a 3d texture yes. Would love to see that option added if you have time.

Are the textures seamless on x,y and z axis when used in a 3d texture?

**Comment by jjxtra** [comment]
I just checked the shape tga file (packed) and it is not seamless on the x and y axis, I think this is what is causing the lines in my clouds. See here:

![image](https://user-images.githubusercontent.com/1271832/47101336-01ac5a80-d1f7-11e8-9e4c-e98a90064886.png)

**Comment by jjxtra** [comment]
The erosion texture does not have this problem.

**Comment by sebh** [comment]
Yes they are supposed to be seamless: not saying there are no bugs though but we have not found any yet :).
What you highlight is normal because the side on the left is one the opposite side of the texture when the slices are superposed. That is why I was asking about the 3d texture before.

**Comment by jjxtra** [comment]
Ok that's my fault. Stepping through my 3d texture frame by frame looks like they line up, so the lines must be caused by something else. Are you using this in a cloud ray march by chance? Do you have the srrange lines in your implementation?

**Comment by jjxtra** [comment]
I guess I am trying to figure out what is different from the nubis slides.

I'm reading the slides about nubis noise generator which is how I found out about this tool. The perlin-worley value uses a different formula (perlin-worley = remap(perlin, 1.0 - worley, 1.0, 0.0, 1.0)) versus the one in your code (remap(perlinNoise, 0.0, 1.0, worleyFBM, 1.0)) and creates a texture that looks much different from this slide:

![image](https://user-images.githubusercontent.com/1271832/47117329-4d73f980-d221-11e8-9fa6-73e8fa1c49a3.png)

Your Perlin/Worley noise:

![image](https://user-images.githubusercontent.com/1271832/47117843-c32c9500-d222-11e8-98f7-c297d220dda4.png)

**Comment by sebh** [comment]
Yes so this repository generate noise function similar to the one in Nubis but I do not say it is exactly same (still, I based it on what is in GPU Pro 7). The code does use the remap for PerlinWorleyNoise. Up to you to change the formula if you want more contrast (maybe there is a mistake but works well when used in engine so far). 

My only worry here is if it is non tileable. I can look at that that at some point when I will find the time...

**Comment by sebh** [comment]
I have clarified the situation with the noise and added another possibiliies that matches the image you shared.
See https://github.com/sebh/TileableVolumeNoise/commit/f81c7b1f34557b9990dc616198067614531a9272 (added the other option but commented out)
Just another possibility. It is unclear which one is used really in their case since the GPUPro7 text describe an approach that will always result in bright texture (the original code).

**Comment by sebh** [comment]
https://github.com/sebh/TileableVolumeNoise/commit/d71af28ea40e0b05cea03fc65aa480aa750e0fd6
commit adds a debug view of few slices slices with a 3x3 repetition tile pattern. (has to be enabled in code to spit out the images). 
==> I could not see any issues.

It is probably the usage you are doing with it. All I see are super large texel and artefact due to bilinear interpolation of texels (or the processing you do in teh pixel shader, or post process, etc.). I will close this for now then since I cannot see any issuse with the data that is there by default. 

However, please come back when you have a definite proof that the source material is broken :)

**Comment by jjxtra** [comment]
Thanks for taking the time to review this, I have tweaked some parameters and have a nice result now that looks good in the sky.
